customer:
  port: 3333
  discovery:
    port: 1111
  docker:
    datasource: jdbc:mysql://localhost:3306/microservices_cust
    

#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  jpa:
    hibernate:
      ddl-auto: none  
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_cust
    username: root
    password: test    

server:
  port: ${customer.port}       
---

spring:
  profiles: dev
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${customer.discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true

    
---

spring:
  profiles: docker
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:${customer.discovery.port}/eureka/ # using eureka instead of localhost
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true